Repository 4IRL/urls4irl, pull requests merged in 2023-12, with the labels that each got.

#119 Add user agent to url validation
  requirements.txt
  tests/unit/test_url_validation.py
  urls4irl/static/scripts/bootstrap.bundle.min.js
  urls4irl/static/scripts/bootstrap.min.js
  urls4irl/static/scripts/jquery-3.6.0.js
  urls4irl/urls/routes.py
  urls4irl/utils/url_validation.py
Labels: bug

#124 Fix register modal and email error notification
  src/templates/email_validation/email_needs_validation_modal.html
  src/templates/register_user.html
  src/users/routes.py
Labels: backend, frontend

#134 Get CDN vs Local JS Bundles
  run.py
  src/__init__.py
  src/config.py
  src/static/scripts/splash.js
  src/static/styles/app.css
  src/templates/email_validation/email_needs_validation_modal.html
  src/templates/layout.html
  src/templates/login.html
  src/templates/password_reset/forgot_password.html
  src/templates/register_user.html
  src/templates/splash.html
Labels: enhancement, backend, frontend

#136 Integrate Favicon
  src/static/favicon/about.txt
  src/static/favicon/android-chrome-192x192.png
  src/static/favicon/android-chrome-512x512.png
  src/static/favicon/apple-touch-icon.png
  src/static/favicon/favicon-16x16.png
  src/static/favicon/favicon-32x32.png
  src/static/favicon/favicon.ico
  src/static/favicon/site.webmanifest
  src/static/styles/app.css
  src/templates/layout.html
Labels: enhancement, frontend

#137 Add Error Page Handling for 404 Status Code
  src/__init__.py
  src/main/routes.py
  src/static/scripts/dragdropswap.js
  src/static/scripts/login.js
  src/tags/routes.py
  src/templates/error_pages/404_response.html
  src/urls/routes.py
  src/users/routes.py
  src/utils/error_handler.py
  src/utubs/routes.py
  tests/functional/test_add_tag_to_url_route.py
  tests/functional/test_add_url_to_utub_route.py
  tests/functional/test_add_user_to_utub_route.py
  tests/functional/test_add_utub_route.py
  tests/functional/test_register_user.py
  tests/functional/test_update_tag_on_url_route.py
  tests/functional/test_update_url_and_desc_route.py
  tests/functional/test_update_utub_desc_route.py
  tests/functional/test_update_utub_name_route.py
  tests/unit/test_register_form.py
Labels: enhancement, backend, frontend

#138 Change url description to title
  src/models.py
  src/urls/forms.py
  src/urls/routes.py
  src/utils/strings.py
  tests/conftest.py
  tests/functional/test_add_url_to_utub_route.py
  tests/functional/test_update_url_and_title_route.py
  tests/models_for_test.py
Labels: enhancement, backend

#145 Users frontend
  src/static/scripts/urls.js
  src/static/scripts/users.js
  src/static/scripts/utubs.js
  src/templates/home.html
Labels: frontend

#148 Change padding under navbar to 50px
  src/static/styles/app.css
Labels: frontend

#150 Create singleton containing flask defined routes for frontend
  src/templates/_routes.html
  src/templates/layout.html
Labels: enhancement, frontend
