Repository 4IRL/urls4irl, pull requests merged in 2023-01, with the labels that each got.

#54 Backend testing
  run.py
  tests/conftest.py
  tests/functional/test_add_tag_to_url_route.py
  tests/functional/test_add_url_to_utub_route.py
  tests/functional/test_add_user_to_utub_route.py
  tests/functional/test_add_utub_route.py
  tests/functional/test_delete_utub_route.py
  tests/functional/test_login_register_home_screen.py
  tests/functional/test_login_user.py
  tests/functional/test_register_user.py
  tests/functional/test_remove_tag_from_url_route.py
  tests/functional/test_remove_url_from_utub_route.py
  tests/functional/test_remove_user_from_utub_route.py
  tests/models_for_test.py
  tests/test_routes.py
  tests/unit/test_db_exists.py
  tests/unit/test_login_form.py
  tests/unit/test_model_serialization.py
  tests/unit/test_models.py
  tests/unit/test_register_form.py
  tests/unit/test_url_validation.py
  tests/utils_for_test.py
  urls4irl/config.py
  urls4irl/main/routes.py
  urls4irl/models.py
  urls4irl/tags/forms.py
  urls4irl/tags/routes.py
  urls4irl/url_validation.py
  urls4irl/urls/forms.py
  urls4irl/urls/routes.py
  urls4irl/users/routes.py
  urls4irl/utubs/routes.py
Labels: backend

#55 Backend
  run.py
  tests/conftest.py
  tests/functional/test_add_tag_to_url_route.py
  tests/functional/test_add_url_to_utub_route.py
  tests/functional/test_add_user_to_utub_route.py
  tests/functional/test_add_utub_route.py
  tests/functional/test_delete_utub_route.py
  tests/functional/test_login_register_home_screen.py
  tests/functional/test_login_user.py
  tests/functional/test_register_user.py
  tests/functional/test_remove_tag_from_url_route.py
  tests/functional/test_remove_url_from_utub_route.py
  tests/functional/test_remove_user_from_utub_route.py
  tests/models_for_test.py
  tests/test_routes.py
  tests/unit/test_db_exists.py
  tests/unit/test_login_form.py
  tests/unit/test_model_serialization.py
  tests/unit/test_models.py
  tests/unit/test_register_form.py
  tests/unit/test_url_validation.py
  tests/utils_for_test.py
  urls4irl/config.py
  urls4irl/main/routes.py
  urls4irl/models.py
  urls4irl/tags/forms.py
  urls4irl/tags/routes.py
  urls4irl/url_validation.py
  urls4irl/urls/forms.py
  urls4irl/urls/routes.py
  urls4irl/users/routes.py
  urls4irl/utubs/routes.py
Labels: backend

#56 Frontend into Dev with Backend Tests
  urls4irl/static/scripts/230103_home.js
  urls4irl/static/scripts/home.js
  urls4irl/static/scripts/tags.js
  urls4irl/static/scripts/urls.js
  urls4irl/static/scripts/utubs.js
  urls4irl/static/styles/app.css
  urls4irl/templates/home.html
  urls4irl/templates/layout.html
Labels: frontend

#57 Backend - UTub Description can be updated
  tests/functional/test_remove_tag_from_url_route.py
  tests/functional/test_remove_url_from_utub_route.py
  tests/functional/test_update_utub_desc_route.py
  urls4irl/utubs/forms.py
  urls4irl/utubs/routes.py
Labels: backend

#58 Backend
  tests/functional/test_update_utub_desc_route.py
  tests/functional/test_update_utub_name_route.py
  urls4irl/utubs/forms.py
  urls4irl/utubs/routes.py
Labels: backend, frontend
