Repository 4IRL/urls4irl, pull requests merged in 2024-07, with the labels that each got.

#223 Member panel with errors included and additional keyboard event listeners
  src/members/forms.py
  src/splash/forms.py
  src/static/scripts/members.js
  src/static/scripts/members_routes.js
  src/static/scripts/tags.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/app.css
  src/static/styles/home.css
  src/templates/home.html
  src/utils/constants.py
  tests/integration/splash/test_login_register_home_screen.py
  tests/integration/splash/test_register_user.py
Labels: backend, frontend

#224 Feature/dig into jinja
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/styles/home.css
  src/templates/head.html
  src/templates/home.html
  src/templates/home/MemberDeck/AddMemberForm.html
  src/templates/home/MemberDeck/MemberDeck.html
  src/templates/home/MemberDeck/MemberDeckHeaders.html
  src/templates/home/TagsDeck/TagsDeck.html
  src/templates/home/URLDeck/EditUTubDescriptionForm.html
  src/templates/home/URLDeck/EditUTubNameForm.html
  src/templates/home/URLDeck/URLDeck.html
  src/templates/home/URLDeck/URLDeckHeader.html
  src/templates/home/URLDeck/URLDeckSubheader.html
  src/templates/home/UTubDeck/AddUTubForm.html
  src/templates/home/UTubDeck/UTubDeck.html
  src/templates/home/UTubDeck/UTubDeckHeaders.html
  src/templates/layout.html
  src/urls/forms.py
  src/utils/constants.py
  src/utils/strings/ui_testing_strs.py
  tests/functional/conftest.py
  tests/functional/utils_for_test.py
Labels: backend, frontend

#225 Refactor/add edit naming convention
  src/members/routes.py
  src/static/scripts/members.js
  src/static/scripts/members_routes.js
  src/static/scripts/splash.js
  src/static/scripts/splash/emailValidation.js
  src/static/scripts/splash/forgotPassword.js
  src/static/scripts/splash/login.js
  src/static/scripts/splash/register.js
  src/static/scripts/tags.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/home.css
  src/tags/routes.py
  src/templates/_routes_constants.html
  src/templates/home/MemberDeck/AddMemberForm.html
  src/templates/home/URLDeck/URLDeck.html
  src/templates/home/URLDeck/URLDeckHeader.html
  src/templates/home/URLDeck/URLDeckSubheader.html
  src/templates/home/URLDeck/UpdateUTubDescriptionForm.html
  src/templates/home/URLDeck/UpdateUTubNameForm.html
  src/templates/home/UTubDeck/AddUTubForm.html
  src/urls/forms.py
  src/urls/routes.py
  src/urls/utils.py
  src/utils/all_routes.py
  src/utubs/routes.py
  tests/integration/utubmembers/test_add_member_to_utub_route.py
  tests/integration/utubs/test_add_utub_route.py
  tests/integration/utubs/test_update_utub_desc_route.py
  tests/integration/utubs/test_update_utub_name_route.py
  tests/integration/utubtags/test_add_tag_to_url_route.py
  tests/integration/utubtags/test_remove_tag_from_url_route.py
  tests/integration/utubtags/test_update_tag_on_url_route.py
  tests/integration/utuburls/test_add_url_to_utub_route.py
  tests/integration/utuburls/test_update_url_route.py
  tests/integration/utuburls/test_update_url_title_route.py
  true
Labels: backend, frontend

#226 Fixes for some update and create name changes
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
Labels: frontend

#227 Allow GET requests if HEAD not allowed
  src/utils/url_validation.py
Labels: backend

#228 Testing/refactoring/test login test user
  src/mocks/mock_constants.py
  src/splash/utils.py
  src/static/scripts/utubs.js
  src/utils/strings/ui_testing_strs.py
  tests/functional/conftest.py
  tests/functional/locators.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/splash_ui/test_register_user_ui.py
  tests/functional/splash_ui/utils_for_test_register_user.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_add_utub_ui.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
Labels: frontend

#229 Remove (most) edit, add, delete verbiage
  src/API_DOCUMENTATION.md
  src/models/utub_urls.py
  src/models/utubs.py
  src/static/scripts/members.js
  src/static/scripts/members_routes.js
  src/static/scripts/tags.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/home.css
  src/tags/routes.py
  src/templates/_routes_constants.html
  src/templates/home/MemberDeck/CreateMemberForm.html
  src/templates/home/MemberDeck/MemberDeck.html
  src/templates/home/MemberDeck/MemberDeckHeaders.html
  src/templates/home/TagsDeck/TagsDeck.html
  src/templates/home/URLDeck/URLDeck.html
  src/templates/home/URLDeck/URLDeckHeader.html
  src/templates/home/URLDeck/URLDeckSubheader.html
  src/templates/home/URLDeck/UpdateUTubDescriptionForm.html
  src/templates/home/URLDeck/UpdateUTubNameForm.html
  src/templates/home/UTubDeck/CreateUTubForm.html
  src/templates/home/UTubDeck/UTubDeck.html
  src/templates/home/UTubDeck/UTubDeckHeaders.html
  src/urls/forms.py
  src/urls/routes.py
  src/utils/all_routes.py
  src/utils/strings/tag_strs.py
  src/utubs/forms.py
  tests/integration/utubtags/test_remove_tag_from_url_route.py
  tests/integration/utubtags/test_update_tag_on_url_route.py
  tests/integration/utuburls/test_update_url_route.py
Labels: backend, frontend

#230 Testing/frontend/members UI/add member
  src/static/scripts/members.js
  src/static/scripts/members_routes.js
  src/templates/home/MemberDeck/CreateMemberForm.html
  tests/functional/conftest.py
  tests/functional/locators.py
  tests/functional/members_ui/test_create_member_ui.py
  tests/functional/members_ui/utils_for_test_members_ui.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/splash_ui/test_register_user_ui.py
  tests/functional/splash_ui/utils_for_test_splash_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/conftest.py
  tests/functional/utubs_ui/test_create_utub_ui.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
  tests/functional/utubs_ui/utils_for_test_utub_ui.py
Labels: frontend

#231 Feature: Thin url cards
  src/static/scripts/members.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/app.css
  src/static/styles/home.css
  src/templates/home/URLDeck/CreateURLForm.html
  src/templates/home/URLDeck/URLDeck.html
  src/utils/strings/url_validation_strs.py
  src/utils/url_validation.py
Labels: backend, frontend

#232 Fix wayback cache attempt, and refactor internet cache into own function
  src/utils/strings/url_validation_strs.py
  src/utils/url_validation.py
Labels: backend

#233 Utub title now editable in thin url card
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs_routes.js
  src/static/styles/home.css
  src/templates/_routes_constants.html
Labels: frontend

#234 Feature/update url string
  src/static/scripts/members.js
  src/static/scripts/tags.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/home.css
  src/templates/_routes_constants.html
  src/utils/strings/url_validation_strs.py
  src/utils/url_validation.py
  tests/unit/test_url_validation.py
Labels: backend, frontend

#235 Prevent duplicate URLs in UTub when updating a URL
  src/API_DOCUMENTATION.md
  src/urls/routes.py
  tests/integration/utuburls/test_update_url_route.py
Labels: backend

#236 Feature/create url tag
  src/static/scripts/members_routes.js
  src/static/scripts/tags.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs_routes.js
  src/static/styles/app.css
  src/static/styles/home.css
  src/tags/forms.py
  src/tags/routes.py
  src/templates/_routes_constants.html
  src/utils/all_routes.py
  src/utils/constants.py
Labels: frontend

#238 Update requirements for fix to vscode pytest discovery
  requirements-dev.txt
  requirements-prod.txt
  requirements-test.txt
Labels: bug, backend

#239 Testing/frontend/members UI/delete member
  src/utils/strings/ui_testing_strs.py
  tests/functional/conftest.py
  tests/functional/locators.py
  tests/functional/members_ui/test_create_member_ui.py
  tests/functional/members_ui/test_delete_member_ui.py
  tests/functional/members_ui/utils_for_test_members_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
Labels: frontend

#240 Handle Stale Data on Frontend
  .github/workflows/test.yml
  src/API_DOCUMENTATION.md
  src/__init__.py
  src/models/utub_urls.py
  src/static/scripts/members.js
  src/static/scripts/members_routes.js
  src/static/scripts/tags.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utubs.js
  src/static/styles/app.css
  src/static/styles/home.css
  src/tags/routes.py
  src/templates/_routes_constants.html
  src/templates/home/URLDeck/URLDeck.html
  src/urls/routes.py
  src/utils/all_routes.py
  src/utils/strings/model_strs.py
  src/utils/strings/url_strs.py
  tests/conftest.py
  tests/integration/utubs/test_get_detailed_utub_info.py
  tests/integration/utubtags/test_add_tag_to_url_route.py
  tests/integration/utubtags/test_remove_tag_from_url_route.py
  tests/integration/utubtags/test_update_tag_on_url_route.py
  tests/integration/utuburls/test_add_url_to_utub_route.py
  tests/integration/utuburls/test_get_url_in_utub_route.py
  tests/integration/utuburls/test_remove_url_from_utub_route.py
  tests/integration/utuburls/test_update_url_route.py
  tests/integration/utuburls/test_update_url_title_route.py
  tests/models_for_test.py
  tests/unit/test_model_serialization.py
Labels: enhancement, backend, frontend

#245 Leave utub test
  src/static/scripts/members.js
  src/static/scripts/members_routes.js
  src/static/scripts/utils.js
  src/utils/strings/ui_testing_strs.py
  tests/functional/conftest.py
  tests/functional/locators.py
  tests/functional/members_ui/test_delete_member_ui.py
  tests/functional/members_ui/test_leave_utub.py
  tests/functional/members_ui/utils_for_test_members_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
Labels: frontend

#246 Keyboard up-down selection for URLs
  src/static/scripts/urls.js
  src/static/scripts/utils.js
  src/static/scripts/utubs_routes.js
Labels: frontend

#250 Feature/focus blur on input text box focus
  src/static/scripts/members.js
  src/static/scripts/members_routes.js
  src/static/scripts/splash.js
  src/static/scripts/splash/emailValidation.js
  src/static/scripts/splash/forgotPassword.js
  src/static/scripts/splash/login.js
  src/static/scripts/splash/register.js
  src/static/scripts/splash/resetPassword.js
  src/static/scripts/tags.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/home.css
  src/templates/home/MemberDeck/CreateMemberForm.html
  src/templates/home/MemberDeck/MemberDeckHeaders.html
  src/templates/home/URLDeck/CreateURLForm.html
  src/templates/home/URLDeck/URLDeckHeader.html
  src/templates/home/UTubDeck/CreateUTubForm.html
  src/templates/home/UTubDeck/UTubDeckHeaders.html
Labels: frontend

#251 Feature/tab indexes for forms
  src/static/scripts/members.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/styles/app.css
  src/static/styles/home.css
Labels: frontend

#253 Feature/tag filtering
  src/static/scripts/members.js
  src/static/scripts/tags.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/home.css
  src/templates/_routes_constants.html
  src/templates/home/MemberDeck/MemberDeckHeaders.html
  src/templates/home/UTubDeck/UTubDeckHeaders.html
  src/utils/constants.py
Labels: enhancement, frontend

#254 UTub selectors blur and focus with UI updating
  src/static/scripts/utubs.js
  src/static/styles/app.css
  src/static/styles/home.css
  src/templates/home/UTubDeck/UTubDeck.html
Labels: frontend

#255 Cite splash image
  src/static/styles/splash.css
Labels: frontend

#262 Feature/utub deck loading icon
  src/static/scripts/members_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/app.css
  src/static/styles/home.css
  src/templates/home/UTubDeck/UTubDeckHeaders.html
Labels: frontend

#265 Working mobile website
  src/static/scripts/members.js
  src/static/scripts/members_routes.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/app.css
  src/static/styles/home.css
  src/static/styles/splash.css
  src/templates/components/navHomeItems.html
  src/templates/components/navSplashItems.html
  src/templates/components/navbar.html
  src/templates/home.html
  src/templates/home/URLDeck/UpdateUTubDescriptionForm.html
  src/templates/home/URLDeck/UpdateUTubNameForm.html
  src/templates/layout.html
  src/templates/splash.html
Labels: enhancement, frontend

#267 Application docker-able
  Dockerfile
  compose.yaml
  migrations/versions/7e471df15dfa_.py
  migrations/versions/a24a7134a8a3_.py
  migrations/versions/ba14a342e5bb_.py
  migrations/versions/ddfbfc18d879_.py
  src/__init__.py
  src/config.py
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/home.css
  src/utils/strings/config_strs.py
Labels: enhancement, backend

#271 Create LICENSE
  LICENSE
Labels: documentation

#273 Testing/frontend/tags UI 2
  src/static/scripts/members_routes.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utubs_routes.js
  src/static/styles/home.css
  src/utils/strings/ui_testing_strs.py
  tests/functional/conftest.py
  tests/functional/locators.py
  tests/functional/members_ui/test_create_member_ui.py
  tests/functional/members_ui/test_delete_member_ui.py
  tests/functional/members_ui/test_leave_utub.py
  tests/functional/members_ui/utils_for_test_members_ui.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/splash_ui/test_register_user_ui.py
  tests/functional/splash_ui/utils_for_test_splash_ui.py
  tests/functional/tags_ui/test_create_tag_ui.py
  tests/functional/tags_ui/test_delete_tag_ui.py
  tests/functional/tags_ui/test_filter_tag_ui.py
  tests/functional/tags_ui/utils_for_test_tag_ui.py
  tests/functional/urls_ui/test_access_url_ui.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/urls_ui/test_delete_url_ui.py
  tests/functional/urls_ui/test_update_url_ui.py
  tests/functional/urls_ui/utils_for_test_url_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_create_utub_ui.py
  tests/functional/utubs_ui/utils_for_test_utub_ui.py
Labels: frontend

#275 Update docker file permissions
  Dockerfile
  DockerfileDev
  src/utils/url_validation.py
  tests/unit/test_url_validation.py
Labels: Infrastructure

#277 Sessions to redis
  .gitignore
  migrations/versions/f75f3a0c5e6f_.py
  requirements-prod.txt
  src/__init__.py
  src/config.py
  tests/conftest.py
  tests/integration/cli/test_cli_manage_db.py
  tests/unit/test_db_exists.py
  tests/utils_for_test.py
Labels: backend, Infrastructure

#278 Feature/tags to utub tags
  migrations/versions/d1444b5d08bb_convert_tags_to_utubtags.py
  migrations/versions/f75f3a0c5e6f_.py
  requirements-prod.txt
  src/API_DOCUMENTATION.md
  src/__init__.py
  src/config.py
  src/mocks/mock_constants.py
  src/mocks/mock_data/tags.py
  src/mocks/mock_options.py
  src/models/utub_tags.py
  src/models/utub_url_tags.py
  src/models/utub_urls.py
  src/models/utubs.py
  src/static/scripts/splash/emailValidation.js
  src/static/scripts/splash/login.js
  src/static/scripts/splash/register.js
  src/static/scripts/splash/resetPassword.js
  src/static/scripts/tags.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/tags/routes.py
  src/tags/url_tag_routes.py
  src/templates/_routes_constants.html
  src/urls/routes.py
  src/utils/all_routes.py
  src/utils/strings/model_strs.py
  src/utils/strings/tag_strs.py
  src/utils/strings/url_strs.py
  src/utubs/routes.py
  tests/conftest.py
  tests/functional/conftest.py
  tests/integration/cli/test_cli_add_mock_data.py
  tests/integration/cli/test_cli_manage_db.py
  tests/integration/cli/utils.py
  tests/integration/utubs/test_delete_utub_route.py
  tests/integration/utubs/test_get_detailed_utub_info.py
  tests/integration/utubtags/conftest.py
  tests/integration/utubtags/test_add_tag_to_url_route.py
  tests/integration/utubtags/test_remove_tag_from_url_route.py
  tests/integration/utubtags/test_update_tag_on_url_route.py
  tests/integration/utuburls/conftest.py
  tests/integration/utuburls/test_get_url_in_utub_route.py
  tests/integration/utuburls/test_remove_url_from_utub_route.py
  tests/integration/utuburls/test_update_url_route.py
  tests/integration/utuburls/test_update_url_title_route.py
  tests/models_for_test.py
  tests/unit/test_db_exists.py
  tests/unit/test_model_serialization.py
  tests/unit/test_models.py
  tests/utils_for_test.py
Labels: backend

#279 Handle Tags table nonexistent for migration
  migrations/versions/d1444b5d08bb_convert_tags_to_utubtags.py
Labels: backend, Infrastructure

#280 Retry hotfix
  migrations/versions/d1444b5d08bb_convert_tags_to_utubtags.py
Labels: backend
