Repository 4IRL/urls4irl, pull requests merged in 2024-04, with the labels that each got.

#179 Run Tests in Parallel
  .github/workflows/u4i_actions.yml
  pytest.ini
  tests/conftest.py
  tests/integration/splash/test_email_validation.py
  tests/integration/splash/test_forgot_password.py
  tests/integration/splash/test_login_register_home_screen.py
  tests/integration/splash/test_login_user.py
  tests/integration/splash/test_register_user.py
  tests/integration/splash/test_reset_password.py
  tests/integration/utubmembers/test_add_member_to_utub_route.py
  tests/integration/utubmembers/test_remove_member_from_utub_route.py
  tests/integration/utubs/test_add_utub_route.py
  tests/integration/utubs/test_delete_utub_route.py
  tests/integration/utubs/test_update_utub_desc_route.py
  tests/integration/utubs/test_update_utub_name_route.py
  tests/integration/utubtags/test_add_tag_to_url_route.py
  tests/integration/utubtags/test_remove_tag_from_url_route.py
  tests/integration/utubtags/test_update_tag_on_url_route.py
  tests/integration/utuburls/test_add_url_to_utub_route.py
  tests/integration/utuburls/test_remove_url_from_utub_route.py
  tests/integration/utuburls/test_update_url_and_title_route.py
  tests/integration/utuburls/test_update_url_route.py
  tests/integration/utuburls/test_update_url_title_route.py
  tests/unit/test_db_exists.py
  tests/unit/test_login_form.py
  tests/unit/test_model_serialization.py
  tests/unit/test_models.py
  tests/unit/test_register_form.py
  tests/unit/test_url_validation.py
Labels: enhancement, backend

#177 Subheader fix
  src/static/scripts/tags.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/users.js
  src/static/scripts/users_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/app.css
  src/templates/_routes.html
  src/templates/home.html
Labels: frontend

#184 Add summary for deployment action and check errors
  .github/workflows/dev-deploy.yml
Labels: enhancement, backend

#185 Fixing output statement for dev deploy action
  .github/workflows/dev-deploy.yml
Labels: documentation

#186 Util route for 404 page
  .github/workflows/dev-deploy.yml
  src/splash/routes.py
  src/static/scripts/splash.js
  src/static/scripts/splash/emailValidation.js
  src/static/scripts/splash/forgotPassword.js
  src/static/scripts/splash/login.js
  src/templates/_routes.html
Labels: enhancement, backend, frontend

#187 Revision/css cleanup
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/styles/app.css
  src/static/styles/home.css
  src/static/styles/splash.css
  src/templates/components/navbar.html
  src/templates/layout.html
Labels: frontend

#188 Fixes to UTub api documentation
  src/README.md
Labels: documentation

#189 Separate models into their own files for easier access
  src/members/forms.py
  src/members/routes.py
  src/models.py
  src/models/__init__.py
  src/models/email_validations.py
  src/models/forgot_passwords.py
  src/models/tags.py
  src/models/url_tags.py
  src/models/urls.py
  src/models/users.py
  src/models/utils.py
  src/models/utub_members.py
  src/models/utub_urls.py
  src/models/utubs.py
  src/splash/forms.py
  src/splash/routes.py
  src/splash/utils.py
  src/tags/routes.py
  src/urls/routes.py
  src/users/routes.py
  src/utils/email_validation.py
  src/utubs/routes.py
  tests/conftest.py
  tests/integration/splash/conftest.py
  tests/integration/splash/test_email_validation.py
  tests/integration/splash/test_forgot_password.py
  tests/integration/splash/test_login_user.py
  tests/integration/splash/test_register_user.py
  tests/integration/splash/test_reset_password.py
  tests/integration/utubmembers/conftest.py
  tests/integration/utubmembers/test_add_member_to_utub_route.py
  tests/integration/utubmembers/test_remove_member_from_utub_route.py
  tests/integration/utubs/conftest.py
  tests/integration/utubs/test_add_utub_route.py
  tests/integration/utubs/test_delete_utub_route.py
  tests/integration/utubs/test_get_detailed_utub_info.py
  tests/integration/utubs/test_update_utub_desc_route.py
  tests/integration/utubs/test_update_utub_name_route.py
  tests/integration/utubtags/conftest.py
  tests/integration/utubtags/test_add_tag_to_url_route.py
  tests/integration/utubtags/test_remove_tag_from_url_route.py
  tests/integration/utubtags/test_update_tag_on_url_route.py
  tests/integration/utuburls/conftest.py
  tests/integration/utuburls/test_add_url_to_utub_route.py
  tests/integration/utuburls/test_remove_url_from_utub_route.py
  tests/integration/utuburls/test_update_url_route.py
  tests/integration/utuburls/test_update_url_title_route.py
  tests/unit/test_db_exists.py
  tests/unit/test_model_serialization.py
  tests/unit/test_models.py
Labels: enhancement, backend

#190 Fix headers for url validation
  src/urls/routes.py
  src/utils/strings/url_validation_strs.py
  src/utils/url_validation.py
  tests/unit/test_url_validation.py
Labels: bug, documentation, backend
