Repository 4IRL/urls4irl, pull requests merged in 2024-01, with the labels that each got.

#152 Rate limiting
  requirements.txt
  src/__init__.py
  src/static/scripts/splash.js
  src/utils/error_handler.py
  src/utils/strings.py
Labels: enhancement, backend

#153 Separate modals and components
  src/static/scripts/urls.js
  src/templates/components/navbar.html
  src/templates/home.html
  src/templates/layout.html
  src/templates/modals/homeModalBase.html
  src/templates/modals/splashModalBase.html
Labels: enhancement, frontend

#154 Enter esc crud bind
  src/static/scripts/dragdropswap.js
  src/static/scripts/urls.js
  src/static/scripts/users.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
Labels: frontend

#162 Add url title when url already in database
  src/urls/routes.py
  tests/functional/test_add_url_to_utub_route.py
Labels: bug, enhancement, backend

#163 Fix login modal errors not displaying
  src/static/scripts/splash.js
Labels: bug, frontend

#164 Add gunicorn to requirements
  migrations/versions/7e471df15dfa_.py
  migrations/versions/a24a7134a8a3_.py
  migrations/versions/ba14a342e5bb_.py
  migrations/versions/ddfbfc18d879_.py
  requirements.txt
  src/models.py
  src/utils/email_validation.py
  src/utils/url_validation.py
Labels: enhancement

#169 Upgrade greenlet to 2.0.2
  requirements.txt
Labels: backend
