Repository 4IRL/urls4irl, pull requests merged in 2024-06, with the labels that each got.

#203 UrlID to UtubUrlID
  src/API_DOCUMENTATION.md
  src/models/tags.py
  src/models/urls.py
  src/models/utub_url_tags.py
  src/models/utub_urls.py
  src/models/utubs.py
  src/tags/routes.py
  src/templates/_routes.html
  src/urls/routes.py
  src/utils/strings/model_strs.py
  src/utils/strings/url_strs.py
  src/utubs/routes.py
  tests/conftest.py
  tests/integration/splash/test_forgot_password.py
  tests/integration/splash/test_reset_password.py
  tests/integration/utubmembers/test_add_member_to_utub_route.py
  tests/integration/utubmembers/test_remove_member_from_utub_route.py
  tests/integration/utubs/test_add_utub_route.py
  tests/integration/utubs/test_delete_utub_route.py
  tests/integration/utubs/test_get_detailed_utub_info.py
  tests/integration/utubs/test_update_utub_desc_route.py
  tests/integration/utubs/test_update_utub_name_route.py
  tests/integration/utubtags/conftest.py
  tests/integration/utubtags/test_add_tag_to_url_route.py
  tests/integration/utubtags/test_remove_tag_from_url_route.py
  tests/integration/utubtags/test_update_tag_on_url_route.py
  tests/integration/utuburls/conftest.py
  tests/integration/utuburls/test_add_url_to_utub_route.py
  tests/integration/utuburls/test_remove_url_from_utub_route.py
  tests/integration/utuburls/test_update_url_route.py
  tests/integration/utuburls/test_update_url_title_route.py
  tests/models_for_test.py
  tests/unit/test_db_exists.py
  tests/unit/test_model_serialization.py
  tests/unit/test_models.py
Labels: enhancement, backend

#205 CLI for mock data, tests for CLI
  .github/workflows/test.yml
  README.md
  pytest.ini
  src/__init__.py
  src/config.py
  src/db.py
  src/mocks/__init__.py
  src/mocks/mock_constants.py
  src/mocks/mock_data/__init__.py
  src/mocks/mock_data/tags.py
  src/mocks/mock_data/urls.py
  src/mocks/mock_data/users.py
  src/mocks/mock_data/utubmembers.py
  src/mocks/mock_data/utubs.py
  src/mocks/mock_options.py
  src/mocks/utils.py
  tests/conftest.py
  tests/integration/cli/conftest.py
  tests/integration/cli/test_cli_add_mock_data.py
  tests/integration/cli/test_cli_manage_db.py
  tests/requirements.txt
  tests/utils_for_test.py
Labels: documentation, enhancement, backend

#207 Ensure primary key usage for members
  src/members/forms.py
  src/members/routes.py
  src/models/utub_members.py
  src/splash/forms.py
  src/splash/routes.py
  src/splash/utils.py
  src/tags/routes.py
  src/urls/routes.py
  src/utubs/routes.py
  tests/integration/splash/test_login_user.py
  tests/integration/splash/test_register_user.py
  tests/integration/utubmembers/test_add_member_to_utub_route.py
  tests/integration/utubmembers/test_remove_member_from_utub_route.py
  tests/integration/utubs/test_add_utub_route.py
  tests/integration/utubs/test_delete_utub_route.py
  tests/integration/utubtags/test_add_tag_to_url_route.py
  tests/integration/utubtags/test_remove_tag_from_url_route.py
  tests/integration/utuburls/conftest.py
  tests/integration/utuburls/test_update_url_route.py
Labels: enhancement, backend

#211 Revision/utubUrlID reference
  src/static/scripts/urls.js
Labels: frontend

#213 Feature/url edit delete permissions
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/styles/home.css
  src/templates/home.html
Labels: enhancement, frontend

#214 Small env variable refactorings
  run.py
  src/__init__.py
  src/config.py
Labels: enhancement, backend

#216 Shows updates properly after last utub deleted
  src/static/scripts/urls.js
Labels: documentation, frontend

#218 Allows user to use back/forward browser history buttons with UTubs
  src/static/scripts/utubs.js
  src/utils/strings/url_validation_strs.py
  src/utubs/routes.py
  tests/integration/utubs/test_get_detailed_utub_info.py
Labels: enhancement, frontend

#219 UI Refactor for large screen, icon placement, URL card sizing
  src/static/scripts/members.js
  src/static/scripts/tags.js
  src/static/scripts/urls.js
  src/static/scripts/utils.js
  src/static/styles/home.css
  src/templates/home.html
Labels: enhancement, frontend

#217 Initial Selenium Frontend Tests
  requirements-prod.txt
  requirements-test.txt
  src/config.py
  src/static/scripts/utubs.js
  src/templates/components/navbar.html
  src/utils/strings/ui_testing_strs.py
  tests/conftest.py
  tests/functional/conftest.py
  tests/functional/locators.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/splash_ui/test_register_user_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/conftest.py
  tests/functional/utubs_ui/test_add_utub_ui.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
  tests/integration/cli/conftest.py
  tests/utils_for_test.py
  true
Labels: enhancement, backend, frontend

#220 Remove description panel, move member panel, add info to URL validation failure
  src/API_DOCUMENTATION.md
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utubs.js
  src/static/styles/app.css
  src/static/styles/home.css
  src/templates/home.html
  src/templates/layout.html
  src/urls/forms.py
  src/urls/routes.py
  src/utils/constants.py
  src/utils/strings/json_strs.py
  src/utils/url_validation.py
Labels: backend, frontend

#221 Feature/cancel edit url utub
  src/static/scripts/tags.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/static/scripts/utubs.js
  src/static/scripts/utubs_routes.js
  src/static/styles/app.css
  src/static/styles/home.css
  src/templates/home.html
Labels: enhancement, frontend
