Repository 4IRL/urls4irl, pull requests merged in 2024-11, with the labels that each got.

#303 Infra/docker for local dev updates
  .dockerignore
  DockerfileDev
  compose-local.yaml
  migrations/env.py
  migrations/versions/.keep
  migrations/versions/799cc1c01a1c_make_unique_url_per_utub.py
  migrations/versions/d1444b5d08bb_convert_tags_to_utubtags.py
  migrations/versions/d5abefc6c65a_initial_migration.py
  migrations/versions/f75f3a0c5e6f_.py
  src/__init__.py
  src/config.py
  src/models/utub_urls.py
  tests/conftest.py
  tests/unit/test_model_serialization.py
Labels: backend, Infrastructure

#304 Update dev docker workflow due to DockerfileDev updates
  .github/workflows/dev-deploy.yml
  compose-dev.yaml
Labels: bug, Infrastructure

#305 Forgot Password tests complete
  tests/functional/locators.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/splash_ui/test_register_user_ui.py
  tests/functional/utils_for_test.py
Labels: frontend

#306 Home page tests complete.
  .github/workflows/test.yml
  pytest.ini
  tests/conftest.py
  tests/functional/home_ui/test_home_ui.py
  tests/functional/locators.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/utils_for_test.py
Labels: frontend

#307 Remove google cache and fix serialization test
  src/utils/url_validation.py
  tests/unit/test_model_serialization.py
Labels: backend

#308 Add single or multiple custom urls through CLI
  README.md
  src/mocks/mock_data/urls.py
  src/mocks/mock_options.py
  tests/integration/cli/test_cli_add_mock_data.py
  tests/integration/cli/utils.py
Labels: backend, Infrastructure

#309 Testing/frontend/create member input
  tests/functional/locators.py
  tests/functional/members_ui/test_create_member_ui.py
  tests/functional/members_ui/test_delete_member_ui.py
  tests/functional/members_ui/utils_for_test_members_ui.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/splash_ui/test_register_user_ui.py
Labels: frontend

#310 All create UTub tests complete
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_create_utub_ui.py
  tests/functional/utubs_ui/utils_for_test_utub_ui.py
Labels: frontend

#311 Testing/frontend infra/login user via session instead of UI
  DockerfileDev
  src/config.py
  src/mocks/mock_data/users.py
  src/mocks/mock_options.py
  tests/functional/conftest.py
  tests/functional/locators.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/utils_for_test.py
  tests/integration/cli/test_login_user_via_cli.py
Labels: backend, Infrastructure

#313 Testing/frontend/update utub inputs
  tests/functional/locators.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_create_utub_ui.py
  tests/functional/utubs_ui/test_update_utub_ui.py
  tests/functional/utubs_ui/utils_for_test_utub_ui.py
Labels: frontend

#314 Testing/frontend/urls UI
  .github/workflows/CI.yml
  src/config.py
  src/mocks/mock_data/urls.py
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utubs_routes.js
  src/templates/_routes_constants.html
  src/utils/constants.py
  tests/functional/conftest.py
  tests/functional/locators.py
  tests/functional/urls_ui/test_access_url_ui.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/urls_ui/utils_for_test_url_ui.py
  tests/functional/utils_for_test.py
Labels: testing

#315 Add tests for updating URL string and title
  src/static/scripts/urls_routes.js
  tests/functional/locators.py
  tests/functional/urls_ui/test_update_url_ui.py
  tests/functional/urls_ui/utils_for_test_url_ui.py
  tests/functional/utils_for_test.py
Labels: testing

#316 Add create/update/access URLs UI tests to GH actions
  .github/workflows/test.yml
  compose-local.yaml
  pytest.ini
  tests/conftest.py
  tests/functional/urls_ui/test_access_url_ui.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/urls_ui/test_update_url_ui.py
  tests/functional/utils_for_test.py
Labels: Infrastructure, testing

#319 Testing/frontend/delete utub fix
  src/utils/strings/ui_testing_strs.py
  tests/functional/members_ui/test_leave_utub.py
  tests/functional/members_ui/utils_for_test_members_ui.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_create_utub_ui.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
  tests/functional/utubs_ui/test_update_utub_ui.py
  tests/functional/utubs_ui/utils_for_test_utub_ui.py
Labels: frontend

#320 Testing/frontend/create tag input test
  tests/functional/locators.py
  tests/functional/members_ui/test_create_member_ui.py
  tests/functional/tags_ui/test_create_tag_ui.py
  tests/functional/tags_ui/test_filter_tag_ui.py
  tests/functional/tags_ui/utils_for_test_tag_ui.py
  tests/functional/utubs_ui/test_update_utub_ui.py
  tests/functional/utubs_ui/utils_for_test_utub_ui.py
Labels: frontend

#323 Remove dockerfile layers and add tests for up/down keys in selecting URLs
  DockerfileDev
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/urls_ui/test_select_url_ui.py
  tests/functional/urls_ui/utils_for_test_url_ui.py
  tests/functional/utils_for_test.py
Labels: frontend, testing

#324 Update and slim the dev dockerfile, creating a local one in its place
  DockerfileDev
  DockerfileLocal
  compose-local.yaml
  tests/functional/conftest.py
Labels: Infrastructure, testing

#326 Infra/fix dev server and prod redis
  .github/workflows/dev-deploy.yml
  compose-dev.yaml
  compose.yaml
Labels: bug, Infrastructure

#328 Testing/frontend/delete tag tests
  .github/workflows/test.yml
  pytest.ini
  src/static/scripts/urls_routes.js
  tests/conftest.py
  tests/functional/conftest.py
  tests/functional/members_ui/test_delete_member_ui.py
  tests/functional/tags_ui/test_create_tag_ui.py
  tests/functional/tags_ui/test_delete_tag_ui.py
  tests/functional/tags_ui/test_filter_tag_ui.py
  tests/functional/tags_ui/utils_for_test_tag_ui.py
  tests/functional/urls_ui/test_update_url_ui.py
  tests/functional/urls_ui/utils_for_test_url_ui.py
  tests/functional/utils_for_test.py
Labels: frontend

#329 Final splash page key tests added
  tests/functional/home_ui/test_home_ui.py
  tests/functional/members_ui/test_create_member_ui.py
  tests/functional/members_ui/test_delete_member_ui.py
  tests/functional/members_ui/test_leave_utub.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/splash_ui/test_register_user_ui.py
  tests/functional/splash_ui/utils_for_test_splash_ui.py
  tests/functional/tags_ui/test_delete_tag_ui.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_create_utub_ui.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
  tests/functional/utubs_ui/test_update_utub_ui.py
Labels: frontend

#331 Deploy prod and dev only on PR merged, not just closed
  .github/workflows/dev-build-and-deploy.yml
  .github/workflows/prod-build-and-deploy.yml
Labels: Infrastructure
