Repository 4IRL/urls4irl, pull requests merged in 2024-08, with the labels that each got.

#281 Fix scroll on home page
  src/static/styles/app.css
Labels: frontend

#282 Tag filter functionality and test passability restored
  src/static/scripts/tags.js
  tests/functional/tags_ui/test_filter_tag_ui.py
  tests/functional/utils_for_test.py
Labels: frontend

#283 Create/delete UTub Tags
  src/API_DOCUMENTATION.md
  src/__init__.py
  src/tags/forms.py
  src/tags/url_tag_routes.py
  src/tags/utub_tag_routes.py
  src/templates/_routes_constants.html
  src/utils/all_routes.py
  src/utils/strings/html_identifiers.py
  src/utils/strings/tag_strs.py
  tests/integration/utubtags/conftest.py
  tests/integration/utubtags/test_add_tag_to_url_route.py
  tests/integration/utubtags/test_add_tags_to_utub_route.py
  tests/integration/utubtags/test_delete_tag_from_url_route.py
  tests/integration/utubtags/test_delete_tag_from_utub_route.py
Labels: enhancement, backend

#284 Update docker to copy static files to host
  .github/workflows/dev-deploy.yml
  compose-dev.yaml
Labels: bug, backend, Infrastructure
