Repository 4IRL/urls4irl, pull requests merged in 2024-12, with the labels that each got.

#330 Feature/frontend/forgot password back button
  src/static/scripts/splash.js
  src/static/scripts/splash/forgotPassword.js
  src/static/scripts/splash/register.js
  src/templates/password_reset/forgot_password.html
  tests/functional/locators.py
  tests/functional/members_ui/test_create_member_ui.py
  tests/functional/members_ui/test_leave_utub.py
  tests/functional/splash_ui/test_forgot_password_ui.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/splash_ui/test_register_user_ui.py
  tests/functional/splash_ui/utils_for_test_splash_ui.py
  tests/functional/utils_for_test.py
Labels: frontend

#333 Refactor url validation into extensions, mock url validation in tests
  src/__init__.py
  src/config.py
  src/extensions/email_sender/email_sender.py
  src/extensions/url_validation/constants.py
  src/extensions/url_validation/url_validator.py
  src/urls/routes.py
  src/utils/db_uri_builder.py
  src/utils/strings/url_validation_strs.py
  src/utils/url_validation.py
  tests/integration/utuburls/test_add_url_to_utub_route.py
  tests/integration/utuburls/test_update_url_route.py
  tests/ui_test_utils.py
  tests/unit/test_models.py
  tests/unit/test_url_validation.py
Labels: backend, testing

#334 Add tag to utub with tests
  src/static/scripts/members_routes.js
  src/static/scripts/tags.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls.js
  src/static/styles/home.css
  src/templates/home/TagsDeck/CreateUTubTagForm.html
  src/templates/home/TagsDeck/TagsDeck.html
  src/templates/home/UTubDeck/UTubDeckHeaders.html
  tests/functional/locators.py
  tests/functional/tags_ui/test_create_utub_tag_ui.py
  tests/functional/tags_ui/utils_for_test_tag_ui.py
Labels: frontend, testing

#335 Setup database backups
  .gitignore
  DockerfileLocal
  compose-local.yaml
  utils/backup-database.sh
  utils/create_backup_user.sh
Labels: Infrastructure

#337 Configure redis password passed down for prod
  compose.yaml
  src/config.py
Labels: bug, Infrastructure

#346 Backend/allow fallthrough of invalid urls (#345)
  .github/workflows/test.yml
  compose-dev.yaml
  compose-local.yaml
  compose.yaml
  migrations/versions/5895ca590d75_add_valid_column_to_urls.py
  migrations/versions/d5abefc6c65a_initial_migration.py
  src/__init__.py
  src/cli/__init__.py
  src/cli/cli_options.py
  src/cli/mock_constants.py
  src/cli/mock_data/__init__.py
  src/cli/mock_data/tags.py
  src/cli/mock_data/urls.py
  src/cli/mock_data/users.py
  src/cli/mock_data/utubmembers.py
  src/cli/mock_data/utubs.py
  src/cli/mock_options.py
  src/cli/utils.py
  src/config.py
  src/extensions/url_validation/constants.py
  src/extensions/url_validation/url_validator.py
  src/models/urls.py
  src/urls/routes.py
  src/utils/strings/ui_testing_strs.py
  src/utils/strings/url_validation_strs.py
  tests/conftest.py
  tests/functional/members_ui/test_create_member_ui.py
  tests/functional/members_ui/test_delete_member_ui.py
  tests/functional/members_ui/test_leave_utub.py
  tests/functional/tags_ui/test_create_tag_ui.py
  tests/functional/tags_ui/test_delete_tag_ui.py
  tests/functional/urls_ui/test_access_url_ui.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/urls_ui/test_delete_url_ui.py
  tests/functional/urls_ui/test_update_url_ui.py
  tests/functional/utubs_ui/test_create_utub_ui.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
  tests/functional/utubs_ui/test_update_utub_ui.py
  tests/integration/cli/test_add_short_url_domains.py
  tests/integration/cli/test_login_user_via_cli.py
  tests/integration/cli/utils.py
  tests/integration/utuburls/test_add_url_to_utub_route.py
  tests/integration/utuburls/test_update_url_route.py
  tests/unit/test_model_serialization.py
  tests/unit/test_models.py
  tests/unit/test_url_validation.py
Labels: enhancement, backend, Infrastructure

#353 Splash sad path tests
  src/config.py
  src/models/email_validations.py
  src/splash/forms.py
  src/splash/utils.py
  src/utils/constants.py
  src/utils/email_validation.py
  src/utils/strings/email_validation_strs.py
  src/utils/strings/json_strs.py
  src/utils/strings/ui_testing_strs.py
  tests/functional/conftest.py
  tests/functional/home_ui/test_home_ui.py
  tests/functional/locators.py
  tests/functional/members_ui/test_create_member_ui.py
  tests/functional/members_ui/test_delete_member_ui.py
  tests/functional/members_ui/test_leave_utub.py
  tests/functional/splash_ui/test_forgot_password_ui.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/splash_ui/test_register_user_ui.py
  tests/functional/splash_ui/test_reset_password_ui.py
  tests/functional/splash_ui/test_validate_email_ui.py
  tests/functional/splash_ui/utils_for_test_splash_ui.py
  tests/functional/tags_ui/test_create_utub_tag_ui.py
  tests/functional/tags_ui/test_delete_tag_ui.py
  tests/functional/tags_ui/test_filter_tag_ui.py
  tests/functional/urls_ui/test_access_url_ui.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/urls_ui/test_delete_url_ui.py
  tests/functional/urls_ui/test_select_url_ui.py
  tests/functional/urls_ui/test_update_url_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
  tests/functional/utubs_ui/test_update_utub_ui.py
  tests/integration/splash/test_forgot_password.py
  tests/integration/splash/test_login_register_home_screen.py
  tests/integration/splash/test_login_user.py
  tests/integration/splash/test_register_user.py
  tests/unit/test_register_form.py
Labels: frontend, testing

#358 Adds sad path member tests
  tests/functional/conftest.py
  tests/functional/locators.py
  tests/functional/members_ui/test_create_member_ui.py
  tests/functional/members_ui/test_delete_member_ui.py
  tests/functional/members_ui/test_leave_utub.py
  tests/functional/members_ui/utils_for_test_members_ui.py
  tests/functional/urls_ui/test_update_url_ui.py
  tests/functional/urls_ui/utils_for_test_url_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
  tests/ui_test_utils.py
Labels: frontend, testing, desktop
