Repository 4IRL/urls4irl, pull requests merged in 2025-01, with the labels that each got.

#359 Fixed padding issue that emerged with the addition of the creatURL bu…
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/templates/home/URLDeck/URLDeck.html
Labels: bug, frontend

#362 Fix UI gap between top URL and top of URL panel.
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/templates/home/URLDeck/URLDeck.html
Labels: bug, frontend

#360 Fixed padding issue that emerged with the addition of the creatURL bu…
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  src/templates/home/URLDeck/URLDeck.html
Labels: frontend

#364 Backend/fix csrf and xss vulnerabilities
  .github/workflows/test.yml
  compose-local.yaml
  requirements-prod.txt
  src/API_DOCUMENTATION.md
  src/config.py
  src/splash/forms.py
  src/splash/routes.py
  src/tags/forms.py
  src/templates/head.html
  src/urls/forms.py
  src/utils/constants.py
  src/utils/input_sanitization.py
  src/utils/strings/json_strs.py
  src/utubs/forms.py
  src/utubs/routes.py
  tests/conftest.py
  tests/functional/home_ui/test_home_ui.py
  tests/functional/splash_ui/test_forgot_password_ui.py
  tests/functional/splash_ui/test_register_user_ui.py
  tests/functional/splash_ui/test_reset_password_ui.py
  tests/functional/tags_ui/test_create_tag_ui.py
  tests/functional/tags_ui/test_create_utub_tag_ui.py
  tests/functional/urls_ui/test_access_url_ui.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/urls_ui/test_update_url_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_create_utub_ui.py
  tests/functional/utubs_ui/test_update_utub_description_ui.py
  tests/functional/utubs_ui/test_update_utub_name_ui.py
  tests/functional/utubs_ui/utils_for_test_utub_ui.py
  tests/integration/cli/test_add_short_url_domains.py
  tests/integration/utubs/test_add_utub_route.py
  tests/integration/utubs/test_update_utub_desc_route.py
  tests/integration/utubs/test_update_utub_name_route.py
  tests/integration/utubtags/test_add_tag_to_url_route.py
  tests/integration/utubtags/test_add_tags_to_utub_route.py
  tests/integration/utuburls/test_add_url_to_utub_route.py
  tests/integration/utuburls/test_update_url_title_route.py
  tests/unit/test_input_sanitization.py
  tests/unit/test_register_form.py
Labels: backend, testing

#369 Prevent shortening of URLs when attempting validation
  .github/workflows/test.yml
  DockerfileLocal
  src/API_DOCUMENTATION.md
  src/extensions/url_validation/constants.py
  src/extensions/url_validation/url_validator.py
  src/static/scripts/urls_routes.js
  src/static/scripts/utils.js
  src/urls/routes.py
  src/utils/strings/url_strs.py
  src/utils/strings/url_validation_strs.py
  tests/functional/conftest.py
  tests/functional/locators.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_update_utub_description_ui.py
  tests/functional/utubs_ui/test_update_utub_name_ui.py
  tests/functional/utubs_ui/utils_for_test_utub_ui.py
  tests/integration/utuburls/test_add_url_to_utub_route.py
  tests/integration/utuburls/test_update_url_route.py
  tests/unit/test_url_validation.py
Labels: bug, backend, frontend, testing

#373 Ensure update UTub desc btn hidden when no UTub selected, and hidden on home page load
  src/static/scripts/urls.js
  src/static/scripts/utubs_routes.js
  src/templates/home/URLDeck/URLDeckSubheader.html
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
  tests/functional/utubs_ui/test_update_utub_description_ui.py
  tests/functional/utubs_ui/utils_for_test_utub_ui.py
Labels: bug, frontend, testing

#375 Backend/csrf provide own error page
  src/__init__.py
  src/extensions/url_validation/url_validator.py
  src/splash/utils.py
  src/static/scripts/members_routes.js
  src/static/scripts/splash/emailValidation.js
  src/static/scripts/splash/forgotPassword.js
  src/static/scripts/splash/login.js
  src/static/scripts/splash/register.js
  src/static/scripts/splash/resetPassword.js
  src/static/scripts/tags_routes.js
  src/static/scripts/urls_routes.js
  src/static/scripts/utubs_routes.js
  src/templates/error_pages/403_response.html
  src/templates/error_pages/404_response.html
  src/templates/error_pages/error_response.html
  src/utils/error_handler.py
  src/utils/strings/html_identifiers.py
  tests/functional/home_ui/test_home_ui.py
  tests/functional/locators.py
  tests/functional/members_ui/test_create_member_ui.py
  tests/functional/members_ui/test_delete_member_ui.py
  tests/functional/members_ui/test_leave_utub.py
  tests/functional/splash_ui/test_forgot_password_ui.py
  tests/functional/splash_ui/test_login_user_ui.py
  tests/functional/splash_ui/test_register_user_ui.py
  tests/functional/splash_ui/test_reset_password_ui.py
  tests/functional/splash_ui/test_validate_email_ui.py
  tests/functional/splash_ui/utils_for_test_splash_ui.py
  tests/functional/tags_ui/test_create_tag_ui.py
  tests/functional/tags_ui/test_create_utub_tag_ui.py
  tests/functional/tags_ui/test_delete_tag_ui.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/urls_ui/test_delete_url_ui.py
  tests/functional/urls_ui/test_update_url_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_create_utub_ui.py
  tests/functional/utubs_ui/test_delete_utub_ui.py
  tests/functional/utubs_ui/test_update_utub_description_ui.py
  tests/functional/utubs_ui/test_update_utub_name_ui.py
  tests/integration/splash/test_forgot_password.py
  tests/integration/splash/test_login_user.py
  tests/integration/splash/test_register_user.py
  tests/integration/splash/test_reset_password.py
  tests/integration/utubmembers/test_add_member_to_utub_route.py
  tests/integration/utubmembers/test_remove_member_from_utub_route.py
  tests/integration/utubs/test_add_utub_route.py
  tests/integration/utubs/test_delete_utub_route.py
  tests/integration/utubs/test_update_utub_desc_route.py
  tests/integration/utubs/test_update_utub_name_route.py
  tests/integration/utubtags/test_add_tag_to_url_route.py
  tests/integration/utubtags/test_add_tags_to_utub_route.py
  tests/integration/utubtags/test_delete_tag_from_url_route.py
  tests/integration/utubtags/test_delete_tag_from_utub_route.py
  tests/integration/utuburls/test_add_url_to_utub_route.py
  tests/integration/utuburls/test_remove_url_from_utub_route.py
  tests/integration/utuburls/test_update_url_route.py
  tests/integration/utuburls/test_update_url_title_route.py
  tests/unit/test_login_form.py
  tests/unit/test_register_form.py
Labels: backend, frontend, testing

#377 Setup restore scripts for backed up database
  .gitignore
  src/extensions/url_validation/url_validator.py
  src/utils/strings/url_validation_strs.py
  tests/functional/splash_ui/test_forgot_password_ui.py
  tests/functional/splash_ui/utils_for_test_splash_ui.py
  utils/db_backup_loader.sh
Labels: Infrastructure, database
