Repository 4IRL/urls4irl, pull requests merged in 2025-02, with the labels that each got.

#379 Frontend sad path url tests for create URL, and fix for URL validation
  src/extensions/url_validation/url_validator.py
  src/templates/_routes_constants.html
  src/urls/routes.py
  src/utils/strings/ui_testing_strs.py
  tests/functional/conftest.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/urls_ui/test_select_url_ui.py
  tests/functional/urls_ui/utils_for_test_url_ui.py
  tests/functional/utils_for_test.py
  tests/unit/test_url_validation.py
Labels: backend, frontend, testing, desktop

#368 Frontend/tag/remove filters button in header
  src/static/scripts/tags.js
  src/static/styles/home.css
  src/templates/head.html
  src/templates/home/TagsDeck/TagsDeck.html
  tests/functional/locators.py
  tests/functional/tags_ui/test_filter_tag_ui.py
  tests/functional/tags_ui/utils_for_test_tag_ui.py
Labels: frontend

#381 Tests/frontend/sad path url update delete access
  src/static/scripts/urls_routes.js
  tests/functional/tags_ui/test_delete_tag_ui.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/urls_ui/test_delete_url_ui.py
  tests/functional/urls_ui/test_select_url_ui.py
  tests/functional/urls_ui/test_update_url_ui.py
  tests/functional/urls_ui/utils_for_test_url_ui.py
  tests/functional/utils_for_test.py
Labels: frontend, testing, desktop

#382 Tests/frontend/sad path tags UI tests
  src/static/scripts/tags.js
  src/static/scripts/tags_routes.js
  src/static/styles/home.css
  src/templates/home/MemberDeck/MemberDeckHeaders.html
  tests/functional/conftest.py
  tests/functional/locators.py
  tests/functional/tags_ui/test_create_tag_ui.py
  tests/functional/tags_ui/test_create_utub_tag_ui.py
  tests/functional/tags_ui/test_delete_tag_ui.py
  tests/functional/tags_ui/test_filter_tag_ui.py
  tests/functional/tags_ui/utils_for_test_tag_ui.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/urls_ui/utils_for_test_url_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_select_utub_ui.py
  tests/functional/utubs_ui/utils_for_test_utub_ui.py
Labels: backend, frontend, testing

#383 Fix dev static file deployment
  .github/workflows/dev-deploy.yml
Labels: bug

#388 Fix URL coloring bug, add tests for UTub selection
  src/static/scripts/urls.js
  src/static/scripts/urls_routes.js
  tests/functional/locators.py
  tests/functional/urls_ui/test_create_url_ui.py
  tests/functional/utils_for_test.py
  tests/functional/utubs_ui/test_select_utub_ui.py
  tests/functional/utubs_ui/utils_for_test_utub_ui.py
Labels: frontend, testing

#390 Fix local container CLI and mobile upper/lower background
  compose-local.yaml
  migrations/env.py
  pytest.ini
  requirements-dev.txt
  src/cli/mock_options.py
  src/cli/utils.py
  src/static/styles/app.css
  src/static/styles/manifest.webmanifest
  src/templates/error_pages/error_response.html
  src/templates/head.html
  src/templates/login.html
  tests/functional/urls_ui/test_access_url_ui.py
  tests/functional/urls_ui/test_select_url_ui.py
  tests/functional/urls_ui/utils_for_test_url_ui.py
  tests/integration/cli/test_cli_manage_db.py
Labels: frontend

#394 Fix releasing for dev and prod builds
  .github/workflows/CI.yml
  .github/workflows/dev-build-and-deploy.yml
  .github/workflows/prod-build-and-deploy.yml
Labels: Infrastructure

#398 Cache bust with asset version
  src/__init__.py
  src/config.py
  src/templates/email_validation/email_needs_validation_modal.html
  src/templates/email_validation/email_needs_validation_modal_expired.html
  src/templates/head.html
  src/templates/home.html
  src/templates/login.html
  src/templates/password_reset/forgot_password.html
  src/templates/password_reset/reset_password.html
  src/templates/password_reset/reset_password_modal.html
  src/templates/register_user.html
  src/templates/splash.html
  src/utils/strings/config_strs.py
  src/utubs/routes.py
Labels: frontend
